[platformio]
default_envs = elecrow-epaper-hmi

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = lvgl/lvgl@^9.5.0

[env:elecrow-epaper-hmi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = huge_app.csv
board_build.f_cpu = 240000000L
board_build.psram = enabled
build_flags = 
	-Iinclude
	-DLV_CONF_INCLUDE_SIMPLE
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
	-O0
build_unflags = 
	-Os
lib_deps = lvgl/lvgl@^9.5.0
lib_ignore = EPD

[env:native]
platform = native
test_framework = unity
build_flags = 
	-D UNIT_TEST
lib_deps = lvgl/lvgl@^9.5.0
